# Step 1: Build the application
FROM node:latest
# WORKDIR /app
COPY package*.json ./
RUN rm -rf node_modules package-lock.json
COPY . .
RUN npm install
EXPOSE 3000
# RUN npm run start
CMD [ "npm", "run", "start"]