# Step 1: Build the application
FROM node:20 as build-stage
# WORKDIR /app
COPY package*.json ./
RUN rm -rf node_modules package-lock.json
COPY . .
RUN npm install
EXPOSE 8000
RUN npm start
# CMD [ "nodemon", "app.js"]
